#special workspace
bind = Super,A, togglespecialworkspace, anime# Anime workspace
bind = Super+Alt, A, movetoworkspacesilent, anime



#Custom
bind = Ctrl+Super, F, exec, $HOME/Documents/Scripts/nofullscreengame.sh# Nofullscreengame mode
#bind = Super, R, exec, $HOME/Documents/Scripts/resetWallpaper.sh

bindd = Ctrl+Super, F, Toggle bar, global, quickshell:barToggle # Toggle bar

bind = Super, J, exec, $HOME/Documents/Scripts/inputJA.sh #Jp input
# Turn monitor on
bind = $mainMod SHIFT, F1, exec, /home/stach/Documents/Scripts/screenON.sh
