# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

source = $pc/execs.conf

exec-once = [workspace 2 silent] firefox

exec-once = [workspace special:special silent; tile] pavucontrol-qt -t 1

exec-once = [workspace special:terminal silent; fullscreen] kitty

